version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rehearsalscheduler
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  db-data:
